# Generated by Django 5.0.1 on 2024-01-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dept_name",
            field=models.CharField(
                choices=[
                    ("Altar", "Altar"),
                    ("Ankur", "Ankur"),
                    ("Aura", "Aura"),
                    ("Cardroom & Costumes", "Cardroom & Costumes"),
                    ("Holistic Health", "Holistic Health"),
                    ("Hostel Essentials", "Hostel Essentials"),
                    ("InSaight", "InSaight"),
                    ("Kitchen", "Kitchen"),
                    ("Maintenance", "Maintenance"),
                    ("Multimedia", "Multimedia"),
                    ("Music", "Music"),
                    ("Sai Replica", "Sai Replica"),
                    ("Sports", "Sports"),
                    ("Stores", "Stores"),
                    ("Telephone", "Telephone"),
                ],
                max_length=20,
            ),
        ),
    ]
