# Generated by Django 5.0.1 on 2024-01-22 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="frqt_tkt_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_name", models.CharField(blank=True, max_length=50)),
                ("frqt_tkt_name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="frqt_tkt_imgs/")),
                ("fields", models.JSONField()),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "frequently_raised_tkts_table",
            },
        ),
        migrations.CreateModel(
            name="ticket_model",
            fields=[
                (
                    "Ticket_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Department_Name", models.CharField(max_length=30)),
                ("Title", models.CharField(max_length=100)),
                ("Description", models.JSONField()),
                ("is_accepted", models.BooleanField(default=False)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                ("Status", models.JSONField()),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "Accepted_By",
                    models.CharField(
                        default="To Be Accepted", max_length=20, null=True
                    ),
                ),
                (
                    "Raised_By",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Queries_corner",
                "db_table": "tickets",
            },
        ),
        migrations.CreateModel(
            name="comments_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField(max_length=300)),
                ("created_at", models.DateTimeField()),
                (
                    "commented_By",
                    models.ForeignKey(
                        blank=True,
                        default="none",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "for_ticket_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raise_tktapp.ticket_model",
                    ),
                ),
            ],
            options={
                "db_table": "Solutions_corner",
            },
        ),
    ]
